[package]
name = "strata-asm-stf"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-identifiers.workspace = true
strata-l1-txfmt.workspace = true

bitcoin.workspace = true
