[package]
edition = "2021"
name = "strata-rpc-types-new"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
strata-acct-types.workspace = true
strata-identifiers.workspace = true
strata-ol-chain-types-new.workspace = true
strata-primitives.workspace = true
strata-snark-acct-types.workspace = true

serde.workspace = true
