[package]
edition = "2021"
name = "alpen-ee-common"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[features]
default = []
test-utils = ["dep:mockall"]

[dependencies]
alpen-reth-node.workspace = true
strata-acct-types.workspace = true
strata-ee-acct-types.workspace = true
strata-ee-chain-types.workspace = true
strata-identifiers.workspace = true
strata-snark-acct-types.workspace = true

alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types-engine.workspace = true
async-trait.workspace = true
bincode.workspace = true
bitcoin.workspace = true
eyre.workspace = true
mockall = { workspace = true, optional = true }
reth-ethereum-engine-primitives.workspace = true
reth-ethereum-primitives.workspace = true
reth-node-builder.workspace = true
reth-primitives-traits.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
mockall.workspace = true
