[package]
name = "strata-ol-state-support-types"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-asm-manifest-types.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-ol-state-types.workspace = true
strata-snark-acct-types.workspace = true
tracing = { workspace = true, optional = true }

[features]
tracing = ["dep:tracing"]

[lints]
workspace = true
