[package]
# TODO: replace the older ol-chain-types crate with this and remove "-new" suffix
# "-new" is added to maintain compatibility with existing code without disruptive changes
name = "strata-ol-chain-types-new"
version = "0.1.0"
edition = "2024"

[dependencies]
ssz.workspace = true
ssz_derive.workspace = true
ssz_primitives.workspace = true
ssz_types.workspace = true
strata-acct-types.workspace = true
strata-asm-common.workspace = true
strata-codec.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-snark-acct-types.workspace = true
tree_hash.workspace = true
tree_hash_derive.workspace = true

int-enum.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
strata-test-utils-ssz.workspace = true

[dependencies.proptest]
optional = true
workspace = true

[build-dependencies]
ssz_codegen.workspace = true

[features]
test-utils = ["dep:proptest"]

[lints]
workspace = true
