[package]
name = "strata-asm-aux"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
borsh.workspace = true
strata-asm-common.workspace = true
strata-btc-types.workspace = true
strata-merkle.workspace = true
thiserror.workspace = true

[dev-dependencies]
strata-test-utils.workspace = true
