[package]
name = "strata-asm-aux"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
strata-asm-common.workspace = true

[dev-dependencies]
strata-identifiers.workspace = true
