[package]
name = "strata-asm-aux"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
borsh.workspace = true
strata-asm-common.workspace = true
strata-merkle.workspace = true
thiserror.workspace = true
