[package]
edition = "2021"
name = "strata-proofimpl-checkpoint"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
rkyv.workspace = true
strata-checkpoint-types.workspace = true
strata-codec-utils.workspace = true
strata-proofimpl-cl-stf.workspace = true
zkaleido.workspace = true
zkaleido-native-adapter.workspace = true

[dev-dependencies]
