[package]
name = "strata-codec-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
rkyv.workspace = true
strata-codec.workspace = true

ssz.workspace = true
ssz_derive.workspace = true

[lints]
workspace = true
