[package]
name = "strata-asm-common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
borsh.workspace = true
strata-primitives.workspace = true
thiserror.workspace = true
