[package]
name = "strata-asm-common"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
borsh.workspace = true
serde.workspace = true
strata-asm-types.workspace = true
strata-identifiers.workspace = true
strata-l1-txfmt.workspace = true
strata-msg-fmt.workspace = true
thiserror.workspace = true
tracing.workspace = true
