[package]
edition = "2021"
name = "alpen-ee-genesis"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-ee-common.workspace = true
alpen-ee-config.workspace = true
strata-acct-types.workspace = true
strata-ee-acct-types.workspace = true
strata-ee-chain-types.workspace = true
strata-identifiers.workspace = true

eyre.workspace = true
tracing.workspace = true

[dev-dependencies]
