[package]
name = "strata-asm-moho-program-impl"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
borsh.workspace = true
moho-types.workspace = true
strata-asm-common.workspace = true
strata-asm-logs.workspace = true
strata-asm-spec.workspace = true
strata-asm-stf.workspace = true
strata-crypto.workspace = true
strata-predicate.workspace = true
strata-primitives.workspace = true

[dev-dependencies]
strata-test-utils-btc.workspace = true
