[package]
name = "strata-asm-worker"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-asm-spec.workspace = true
strata-asm-stf.workspace = true
strata-asm-types.workspace = true
strata-btc-types.workspace = true
strata-params.workspace = true
strata-primitives.workspace = true
strata-service.workspace = true
strata-state.workspace = true
strata-storage.workspace = true
strata-tasks.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bitcoin.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-test-utils-btcio.workspace = true
strata-test-utils-l2.workspace = true
tokio.workspace = true
bitcoind-async-client.workspace = true
corepc-node = { version = "0.8.0", features = ["29_0"] }
async-trait.workspace = true
