[package]
name = "strata-asm-bridge-msgs"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
arbitrary.workspace = true
rkyv.workspace = true
serde.workspace = true

strata-asm-common.workspace = true
strata-asm-txs-bridge-v1.workspace = true
strata-primitives.workspace = true
