[package]
name = "strata-ee-chunk-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-ee-acct-types.workspace = true
strata-ee-chain-types.workspace = true
strata-snark-acct-types.workspace = true

[lints]
workspace = true
