[package]
name = "strata-ol-da"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-codec.workspace = true
strata-da-framework.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-ol-chain-types-new.workspace = true
strata-snark-acct-types.workspace = true
ssz.workspace = true

thiserror.workspace = true

[lints]
workspace = true
