[package]
name = "strata-ol-da"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-asm-common.workspace = true
strata-asm-txs-checkpoint.workspace = true
strata-btc-types.workspace = true
strata-codec.workspace = true
strata-da-framework.workspace = true
strata-identifiers.workspace = true
strata-l1-txfmt.workspace = true
strata-ledger-types.workspace = true
strata-predicate.workspace = true
strata-snark-acct-types.workspace = true

bitcoin.workspace = true
bitcoind-async-client.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
strata-asm-txs-test-utils.workspace = true
strata-l1-envelope-fmt.workspace = true
strata-ol-params.workspace = true
strata-ol-state-types.workspace = true
