[package]
edition = "2021"
name = "strata-storage"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-checkpoint-types.workspace = true
strata-csm-types.workspace = true
strata-db-store-sled.workspace = true
strata-db-types.workspace = true
strata-identifiers.workspace = true
strata-merkle = { workspace = true, features = ["ssz"] }
strata-ol-chain-types.workspace = true
strata-ol-chain-types-new = { workspace = true, features = ["test-utils"] }
strata-ol-chainstate-types.workspace = true
strata-ol-state-types.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true
strata-storage-common.workspace = true

anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
rkyv.workspace = true
threadpool.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
strata-checkpoint-types-ssz = { workspace = true, features = ["test-utils"] }
strata-db-store-sled.workspace = true
strata-identifiers = { workspace = true, features = ["test-utils"] }
strata-ledger-types.workspace = true
strata-ol-state-types = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
