[package]
name = "strata-ol-params"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
serde.workspace = true
strata-identifiers.workspace = true
strata-predicate.workspace = true

[dev-dependencies]
serde_json.workspace = true
