[package]
edition = "2021"
name = "strata-db-types"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-checkpoint-types.workspace = true
strata-csm-types.workspace = true
strata-identifiers.workspace = true
strata-merkle = { workspace = true, features = ["ssz"] }
strata-ol-chain-types.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-chainstate-types.workspace = true
strata-ol-state-types.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true
strata-storage-common.workspace = true
zkaleido.workspace = true

anyhow.workspace = true
arbitrary.workspace = true
bincode.workspace = true
bitcoin.workspace = true
borsh.workspace = true
parking_lot = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
typed-sled.workspace = true

[features]
default = []
mocks = []
stubs = ["dep:parking_lot"]

[dev-dependencies]
serde_json.workspace = true
