[package]
name = "strata-btc-verification"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-btc-types.workspace = true
strata-crypto.workspace = true
strata-identifiers = { workspace = true, features = ["bitcoin"] }

arbitrary.workspace = true
bitcoin.workspace = true
borsh.workspace = true
rkyv.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
strata-test-utils-btc.workspace = true

rand.workspace = true

[lints]
workspace = true
