[package]
edition = "2021"
name = "strata-test-utils-btc"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-asm-txs-bridge-v1.workspace = true
strata-asm-types.workspace = true
strata-bridge-types = { workspace = true, features = ["test_utils"] }
strata-btcio.workspace = true
strata-identifiers.workspace = true
strata-params.workspace = true
strata-primitives.workspace = true
strata-test-utils.workspace = true

anyhow.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
bitcoind-async-client.workspace = true
corepc-types.workspace = true
hex.workspace = true
tokio.workspace = true
