[package]
edition = "2021"
name = "alpen-reth"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[features]
default = ["sled"]
sled = ["dep:sled", "dep:typed-sled", "alpen-reth-db/sled"]
rocksdb = [
  "alpen-reth-db/rocksdb",
  "dep:rockbound",
  "dep:strata-db-store-rocksdb",
]

[[bin]]
name = "alpen-reth"
path = "src/main.rs"

[dependencies]
alpen-chainspec.workspace = true
alpen-reth-db.workspace = true
alpen-reth-exex.workspace = true
alpen-reth-node.workspace = true
alpen-reth-rpc.workspace = true

clap.workspace = true
eyre.workspace = true
reth-chainspec.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-db.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
rockbound = { workspace = true, optional = true }
sled = { workspace = true, optional = true }
strata-db-store-rocksdb = { workspace = true, optional = true }
tracing.workspace = true
typed-sled = { workspace = true, optional = true }
