[package]
edition = "2021"
name = "alpen-reth"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[[bin]]
name = "alpen-reth"
path = "src/main.rs"

[dependencies]
alpen-chainspec.workspace = true
alpen-reth-db.workspace = true
alpen-reth-exex.workspace = true
alpen-reth-node.workspace = true
alpen-reth-rpc.workspace = true

reth-chainspec.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-db.workspace = true
reth-network.workspace = true
reth-network-api.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-primitives.workspace = true
reth-transaction-pool.workspace = true

clap.workspace = true
eyre.workspace = true
futures-util.workspace = true
sled.workspace = true
tokio.workspace = true
tracing.workspace = true
typed-sled.workspace = true
