[package]
name = "strata-params"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-btc-types.workspace = true
strata-identifiers.workspace = true
strata-l1-txfmt.workspace = true
strata-predicate.workspace = true

bitcoin.workspace = true
rkyv.workspace = true
serde.workspace = true
thiserror.workspace = true
