[package]
name = "strata-ol-state-types"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-codec.workspace = true
strata-codec-utils.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-merkle.workspace = true
strata-snark-acct-types.workspace = true

bitcoin.workspace = true
ssz.workspace = true
tree_hash.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
