[package]
name = "strata-ol-state-types"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-snark-acct-types.workspace = true

[lints]
workspace = true
