[package]
name = "strata-ol-state-types"
version = "0.1.0"
edition = "2024"

[dependencies]
ssz.workspace = true
ssz_derive.workspace = true
ssz_primitives.workspace = true
ssz_types.workspace = true
strata-acct-types.workspace = true
strata-asm-manifest-types.workspace = true
strata-codec.workspace = true
strata-codec-utils.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-merkle.workspace = true
strata-ol-params.workspace = true
strata-predicate.workspace = true
strata-snark-acct-types.workspace = true
tree_hash.workspace = true
tree_hash_derive.workspace = true

proptest = { optional = true, workspace = true }

[build-dependencies]
ssz_codegen.workspace = true

[dev-dependencies]
proptest.workspace = true
strata-identifiers = { workspace = true, features = ["test-utils"] }
strata-ol-params = { workspace = true, features = ["arbitrary"] }
strata-test-utils-ssz.workspace = true

[features]
test-utils = ["dep:proptest", "strata-identifiers/test-utils"]

[lints]
workspace = true
