[package]
name = "strata-test-utils-btcio"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-crypto = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["full", "test-util"] }

anyhow.workspace = true
bitcoin = { workspace = true, features = ["rand"] }
bitcoind-async-client.workspace = true
musig2.workspace = true

# update bitcoind version in CI to match corepc-node feature
corepc-node = { version = "0.8.0", features = ["29_0"] }

[dev-dependencies]
rand.workspace = true
