[package]
name = "strata-test-utils-btcio"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-crypto = { workspace = true, features = ["test-utils"] }
tokio = { workspace = true, features = ["full", "test-util"] }

anyhow.workspace = true
bitcoin = { workspace = true, features = ["rand"] }
bitcoind-async-client.workspace = true
corepc-node.workspace = true
musig2.workspace = true

[dev-dependencies]
rand.workspace = true
