[package]
name = "strata-test-utils-btcio"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bitcoin = { workspace = true, features = ["rand"] }
bitcoind-async-client.workspace = true
corepc-node = { version = "0.8.0", features = ["29_0"] }
musig2.workspace = true
strata-crypto = { workspace = true, features = ["test-utils"] }

[dev-dependencies]
rand.workspace = true
tokio = { workspace = true, features = ["full", "test-util"] }
