[package]
name = "strata"
version = "0.1.0"
edition = "2024"

[features]
default = ["sequencer"]
sequencer = [
  "dep:strata-asm-txs-checkpoint",
  "dep:strata-checkpoint-types-ssz",
  "dep:strata-crypto",
  "dep:strata-key-derivation",
  "dep:strata-l1-txfmt",
  "dep:strata-ol-block-assembly",
  "dep:strata-ol-sequencer",
  "dep:zeroize",
]

[dependencies]
ssz.workspace = true
strata-asm-txs-checkpoint = { workspace = true, optional = true }
strata-asm-worker.workspace = true
strata-btcio.workspace = true
strata-chain-worker-new.workspace = true
strata-checkpoint-types-ssz = { workspace = true, optional = true }
strata-common.workspace = true
strata-config.workspace = true
strata-consensus-logic.workspace = true
strata-crypto = { workspace = true, optional = true }
strata-csm-types.workspace = true
strata-csm-worker.workspace = true
strata-db-store-sled.workspace = true
strata-db-types.workspace = true
strata-identifiers.workspace = true
strata-key-derivation = { workspace = true, optional = true }
strata-l1-txfmt = { workspace = true, optional = true }
strata-ledger-types.workspace = true
strata-node-context.workspace = true
strata-ol-block-assembly = { workspace = true, optional = true }
strata-ol-chain-types-new.workspace = true
strata-ol-checkpoint.workspace = true
strata-ol-genesis.workspace = true
strata-ol-mempool.workspace = true
strata-ol-params.workspace = true
strata-ol-rpc-api.workspace = true
strata-ol-rpc-types.workspace = true
strata-ol-sequencer = { workspace = true, optional = true }
strata-params.workspace = true
strata-primitives.workspace = true
strata-service.workspace = true
strata-snark-acct-types.workspace = true
strata-status.workspace = true
strata-storage.workspace = true
strata-tasks.workspace = true

anyhow.workspace = true
argh.workspace = true
async-trait.workspace = true
bitcoin.workspace = true
bitcoind-async-client.workspace = true
format_serde_error.workspace = true
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde_json.workspace = true
thiserror.workspace = true
threadpool.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
zeroize = { workspace = true, optional = true }

[lints]
workspace = true
