[package]
name = "strata-asm-proto-checkpoint"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-checkpoint-msgs.workspace = true
strata-asm-common.workspace = true
strata-asm-proto-checkpoint-txs.workspace = true
strata-checkpoint-types-ssz.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-predicate.workspace = true
strata-test-utils = { workspace = true, optional = true }

ssz.workspace = true
ssz_primitives.workspace = true

borsh.workspace = true
k256 = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
strata-merkle.workspace = true

[features]
test-utils = ["dep:k256", "dep:rand", "dep:strata-test-utils"]
