[package]
name = "strata-asm-proto-checkpoint"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bitcoin-bosd.workspace = true
ssz.workspace = true
ssz_primitives.workspace = true
strata-asm-bridge-msgs.workspace = true
strata-asm-checkpoint-msgs.workspace = true
strata-asm-common.workspace = true
strata-asm-proto-checkpoint-txs.workspace = true
strata-checkpoint-types-ssz.workspace = true
strata-codec.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-stf.workspace = true
strata-predicate = { workspace = true, features = ["all"] }

borsh.workspace = true
thiserror.workspace = true

[dev-dependencies]
strata-test-utils-l2.workspace = true
