[package]
name = "strata-asm-proto-checkpoint"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-asm-proto-checkpoint-txs.workspace = true
strata-checkpoint-types-ssz.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-predicate.workspace = true

ssz.workspace = true
ssz_primitives.workspace = true

borsh.workspace = true
thiserror.workspace = true
