[package]
name = "strata-db-store-sled"
version = "0.1.0"
edition = "2024"

[dependencies]
ssz.workspace = true
ssz_derive.workspace = true
strata-acct-types.workspace = true
strata-asm-common.workspace = true
strata-checkpoint-types.workspace = true
strata-codec.workspace = true
strata-csm-types.workspace = true
strata-db-types.workspace = true
strata-identifiers = { workspace = true, features = ["test-utils"] }
strata-ol-chain-types.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-chainstate-types.workspace = true
strata-ol-state-types.workspace = true
strata-paas.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true
typed-sled.workspace = true
zkaleido.workspace = true

anyhow.workspace = true
rkyv.workspace = true
sled.workspace = true
ssz_types.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
strata-checkpoint-types-ssz = { workspace = true, features = ["test-utils"] }
strata-db-tests.workspace = true
strata-identifiers = { workspace = true, features = ["test-utils"] }
strata-ol-state-types = { workspace = true, features = ["test-utils"] }
sled = "0.34.7"

[lints]
workspace = true

[features]
default = ["test_utils"]
test_utils = []
