[package]
name = "strata-ol-stf"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-ledger-types.workspace = true
strata-ol-chain-types-new.workspace = true

[lints]
workspace = true
