[package]
name = "strata-ol-stf"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-asm-common.workspace = true
strata-asm-manifest-types.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-msg-fmt.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-da.workspace = true
strata-snark-acct-types.workspace = true

thiserror.workspace = true

[lints]
workspace = true
