[package]
name = "strata-ol-stf"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
tracing.workspace = true

strata-acct-types.workspace = true
strata-asm-common.workspace = true
strata-asm-logs.workspace = true
strata-crypto.workspace = true
strata-ledger-types.workspace = true
strata-ol-chain-types-new.workspace = true
strata-params.workspace = true
strata-primitives.workspace = true
strata-snark-acct-sys.workspace = true
strata-snark-acct-types.workspace = true

[dev-dependencies]
bitcoin.workspace = true
sha2.workspace = true
strata-merkle.workspace = true

strata-btc-types.workspace = true
strata-predicate.workspace = true

[lints]
workspace = true
