[package]
name = "strata-asm-chain-types"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh.workspace = true
serde.workspace = true
strata-identifiers.workspace = true

[lints]
workspace = true
