[package]
name = "strata-da-framework"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-codec.workspace = true

thiserror.workspace = true

[dev-dependencies]
strata-mmr.workspace = true
strata-merkle.workspace = true
sha2.workspace = true
