[package]
name = "strata-identifiers"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-codec.workspace = true

arbitrary.workspace = true
bitcoin = { workspace = true, optional = true }
borsh.workspace = true
const-hex = "1.14"
digest.workspace = true
hex.workspace = true
int-enum.workspace = true
serde.workspace = true
sha2.workspace = true
zeroize.workspace = true

[dev-dependencies]
bitcoin.workspace = true
rand.workspace = true
serde_json.workspace = true
bincode.workspace = true

[features]
default = ["bitcoin"]
bitcoin = ["dep:bitcoin"]
