[package]
name = "strata-identifiers"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ssz.workspace = true
ssz_derive.workspace = true
ssz_primitives.workspace = true
ssz_types = { workspace = true, features = ["serde"] }
strata-codec.workspace = true
tree_hash.workspace = true
tree_hash_derive.workspace = true

arbitrary.workspace = true
bitcoin = { workspace = true, optional = true }
const-hex = "1.14"
hex.workspace = true
int-enum.workspace = true
proptest = { workspace = true, optional = true }
rkyv.workspace = true
serde.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[build-dependencies]
ssz_codegen.workspace = true

[dev-dependencies]
strata-test-utils-ssz.workspace = true

bitcoin.workspace = true
proptest.workspace = true
serde_json.workspace = true

[features]
default = ["bitcoin"]
bitcoin = ["dep:bitcoin"]
test-utils = ["dep:proptest"]
