[package]
edition = "2021"
name = "guest-sp1-evm-ee"
version = "0.1.0"

[workspace]

[dependencies]
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.2" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.8.2" }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp", tag = "reth-1.8.2" }
strata-ee-acct-types = { path = "../../../crates/ee-acct-types" }
strata-ee-chain-types = { path = "../../../crates/ee-chain-types" }
strata-evm-ee = { path = "../../../crates/evm-ee" }
zkaleido = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc17" }
zkaleido-sp1-guest-env = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc17" }

[patch.crates-io]
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.30.0-sp1-5.0.0" }
secp256k1-sys = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.30.0-sp1-5.0.0" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-sha2-0.10.8-sp1-4.0.0", package = "sha2" }
bn = { git = "https://github.com/sp1-patches/bn", tag = "patch-0.6.0-sp1-5.0.0", package = "substrate-bn" }
sha3 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-sha3-0.10.8-sp1-4.0.0" }
k256 = { git = "https://github.com/sp1-patches/elliptic-curves", tag = "patch-k256-13.4-sp1-5.0.0" }

[features]
mock-verify = ["zkaleido-sp1-guest-env/mock-verify"]
zkvm-verify = ["zkaleido-sp1-guest-env/zkvm-verify"]
