[package]
name = "strata-ol-block-assembly"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-db.workspace = true
strata-identifiers.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-mempool.workspace = true
strata-primitives.workspace = true

thiserror.workspace = true
