[package]
name = "strata-ol-block-assembly"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-acct-types.workspace = true
strata-asm-manifest-types.workspace = true
strata-db-types.workspace = true
strata-identifiers.workspace = true
strata-ledger-types.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-mempool.workspace = true
strata-ol-state-types.workspace = true
strata-snark-acct-types.workspace = true
strata-storage.workspace = true

async-trait.workspace = true
thiserror.workspace = true

[dev-dependencies]
strata-db-store-sled.workspace = true
threadpool.workspace = true
