[package]
edition = "2021"
name = "alpen-client"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[features]
default = ["sequencer"]
sequencer = []

[[bin]]
name = "alpen-client"
path = "src/main.rs"

[dependencies]
alpen-chainspec.workspace = true
alpen-ee-common.workspace = true
alpen-ee-config.workspace = true
alpen-ee-database.workspace = true
alpen-ee-engine.workspace = true
alpen-ee-ol-tracker.workspace = true
alpen-reth-evm.workspace = true
alpen-reth-node.workspace = true
strata-acct-types.workspace = true
strata-identifiers.workspace = true
strata-primitives.workspace = true

alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
async-trait.workspace = true
clap.workspace = true
eyre.workspace = true
reth-chainspec.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-db.workspace = true
reth-network.workspace = true
reth-network-api.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-payload-builder.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
strata-snark-acct-types.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
