[package]
edition = "2021"
name = "alpen-client"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[[bin]]
name = "alpen-client"
path = "src/main.rs"

[dependencies]
alpen-chainspec.workspace = true
alpen-reth-node.workspace = true
strata-acct-types.workspace = true
strata-db-store-rocksdb = { workspace = true, optional = true }
strata-ee-acct-runtime.workspace = true
strata-ee-acct-types.workspace = true
strata-identifiers.workspace = true
strata-snark-acct-types.workspace = true

alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
async-trait.workspace = true
clap.workspace = true
eyre.workspace = true
reth-chainspec.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-db.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-provider.workspace = true
rockbound = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
mockall.workspace = true
