[package]
edition = "2021"
name = "alpen-client"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[features]
default = ["sequencer"]
sequencer = [
  "dep:alpen-ee-exec-chain",
  "dep:alpen-ee-sequencer",
  "dep:alpen-reth-evm",
  "dep:alloy-eips",
  "dep:alloy-rpc-types-engine",
  "dep:bitcoin",
  "dep:reth-payload-builder",
]

[[bin]]
name = "alpen-client"
path = "src/main.rs"

[dependencies]
alpen-chainspec.workspace = true
alpen-ee-common.workspace = true
alpen-ee-config.workspace = true
alpen-ee-database.workspace = true
alpen-ee-engine.workspace = true
alpen-ee-exec-chain = { workspace = true, optional = true }
alpen-ee-genesis.workspace = true
alpen-ee-ol-tracker.workspace = true
alpen-ee-sequencer = { workspace = true, optional = true }
alpen-reth-evm = { workspace = true, optional = true }
alpen-reth-node.workspace = true
strata-acct-types.workspace = true
strata-common = { workspace = true, features = ["async"] }
strata-identifiers.workspace = true
strata-ol-rpc-api = { workspace = true, features = ["client"] }
strata-ol-rpc-types.workspace = true
strata-primitives.workspace = true
strata-snark-acct-types.workspace = true

alloy-eips = { workspace = true, optional = true }
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, optional = true }
async-trait.workspace = true
bitcoin = { workspace = true, optional = true }
clap.workspace = true
eyre.workspace = true
jsonrpsee = { workspace = true, features = ["http-client"] }
reth-chainspec.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-cli-util.workspace = true
reth-db.workspace = true
reth-network.workspace = true
reth-network-api.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-payload-builder = { workspace = true, optional = true }
reth-primitives.workspace = true
reth-provider.workspace = true
ssz.workspace = true
threadpool.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
