[package]
name = "strata-asm-proto-bridge-v1"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
arbitrary.workspace = true
bitcoin.workspace = true
bitvec.workspace = true
borsh.workspace = true
rand_chacha.workspace = true
serde.workspace = true
thiserror.workspace = true

strata-asm-bridge-interface.workspace = true
strata-asm-common.workspace = true
strata-asm-logs.workspace = true
strata-asm-txs-bridge-v1.workspace = true
strata-bridge-types.workspace = true
strata-codec.workspace = true
strata-crypto = { workspace = true, features = ["serde"] }
strata-l1-txfmt.workspace = true
strata-primitives.workspace = true

[dev-dependencies]
strata-test-utils.workspace = true
strata-asm-txs-bridge-v1 = { workspace = true, features = ["test-utils"] }
rand.workspace = true
secp256k1.workspace = true
