[package]
name = "strata-asm-proto-checkpoint-v0"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
# ASM dependencies
borsh.workspace = true
strata-asm-bridge-interface.workspace = true
strata-asm-checkpoint-interface.workspace = true
strata-asm-common.workspace = true
strata-asm-logs.workspace = true
strata-asm-proto-checkpoint-txs.workspace = true
strata-checkpoint-types.workspace = true
strata-predicate.workspace = true
strata-primitives.workspace = true
thiserror.workspace = true

[features]
debug-utils = []
