[package]
name = "strata-asm-proto-checkpoint-v0"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
# ASM dependencies
borsh.workspace = true
strata-asm-bridge-msgs.workspace = true
strata-asm-checkpoint-msgs.workspace = true
strata-asm-common.workspace = true
strata-asm-logs.workspace = true
strata-asm-txs-checkpoint-v0.workspace = true
strata-checkpoint-types.workspace = true
strata-identifiers.workspace = true
strata-predicate.workspace = true
strata-primitives.workspace = true
thiserror.workspace = true

[features]
debug-utils = []
