[package]
name = "strata-asm-txs-checkpoint-v0"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ssz.workspace = true
strata-asm-common.workspace = true
strata-bridge-types.workspace = true
strata-checkpoint-types.workspace = true
strata-l1-envelope-fmt.workspace = true
strata-ol-chainstate-types.workspace = true

bitcoin.workspace = true
borsh.workspace = true
thiserror.workspace = true
