[package]
name = "strata-ol-msg-types"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-codec.workspace = true
strata-codec-derive.workspace = true
strata-identifiers.workspace = true
strata-msg-fmt.workspace = true

[lints]
workspace = true
