[package]
edition = "2021"
name = "strata-eectl"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-common.workspace = true
strata-db.workspace = true
strata-ol-chain-types.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true
strata-status.workspace = true
strata-tasks.workspace = true

anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
