[package]
edition = "2021"
name = "strata-eectl"
version = "0.2.0"

[dependencies]
strata-primitives.workspace = true
strata-state.workspace = true

thiserror.workspace = true
prometheus.workspace = true
lazy_static.workspace = true
