[package]
name = "strata-asm-proto-checkpoint-txs"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ssz.workspace = true
strata-asm-common.workspace = true
strata-bridge-types.workspace = true
strata-checkpoint-types.workspace = true
strata-checkpoint-types-ssz.workspace = true
strata-l1-envelope-fmt.workspace = true
strata-ol-chainstate-types.workspace = true

bitcoin.workspace = true
rkyv.workspace = true
thiserror.workspace = true
