[package]
name = "strata-asm-params"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-btc-types.workspace = true
strata-crypto.workspace = true
strata-identifiers.workspace = true
strata-l1-txfmt.workspace = true
strata-predicate.workspace = true

arbitrary = { workspace = true, optional = true }
serde.workspace = true

[features]
arbitrary = ["dep:arbitrary", "strata-predicate/arbitrary"]
