[package]
edition = "2021"
name = "strata-rpc-types"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-asm-proto-bridge-v1.workspace = true
strata-bridge-types.workspace = true
strata-btc-types.workspace = true
strata-checkpoint-types.workspace = true
strata-csm-types.workspace = true
strata-db-types.workspace = true
strata-ol-chain-types.workspace = true
strata-primitives.workspace = true

bitcoin.workspace = true
hex.workspace = true
jsonrpsee = { workspace = true, features = ["server"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
