[package]
name = "strata-ledger-types"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-asm-manifest-types.workspace = true
strata-identifiers.workspace = true
strata-ol-chain-types-new.workspace = true
strata-predicate.workspace = true
strata-snark-acct-types.workspace = true

[lints]
workspace = true
