[package]
edition = "2021"
name = "strata-ol-rpc-types"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
strata-acct-types.workspace = true
strata-checkpoint-types-ssz.workspace = true
strata-identifiers.workspace = true
strata-ol-block-assembly.workspace = true
strata-ol-chain-types-new.workspace = true
strata-ol-mempool.workspace = true
strata-ol-sequencer.workspace = true
strata-primitives.workspace = true
strata-snark-acct-types.workspace = true

hex.workspace = true
serde.workspace = true
ssz.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
