[package]
name = "strata-asm-spec-debug"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-asm-params.workspace = true
strata-asm-proto-checkpoint-v0.workspace = true
strata-asm-proto-debug-v1.workspace = true
strata-asm-spec.workspace = true
strata-l1-txfmt.workspace = true
strata-params.workspace = true
