[package]
edition = "2021"
name = "strata-ol-chain-types"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-crypto.workspace = true
strata-params.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true

arbitrary.workspace = true
borsh.workspace = true
rkyv.workspace = true
serde.workspace = true
ssz.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-test-utils.workspace = true
