[package]
edition = "2021"
name = "strata-proofimpl-cl-stf"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-chainexec.workspace = true
strata-chaintsn.workspace = true
strata-ol-chain-types.workspace = true
strata-ol-chainstate-types.workspace = true
strata-params.workspace = true
strata-primitives.workspace = true
zkaleido.workspace = true
zkaleido-native-adapter.workspace = true

rkyv.workspace = true

[dev-dependencies]
