[package]
edition = "2021"
name = "alpen-ee-engine"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-ee-common.workspace = true
alpen-reth-node.workspace = true
strata-acct-types.workspace = true
strata-common = { workspace = true, features = ["async"] }

alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
async-trait.workspace = true
reth-node-builder.workspace = true
reth-provider.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
alpen-ee-common = { workspace = true, features = ["test-utils"] }
strata-acct-types.workspace = true
strata-ee-acct-types.workspace = true
strata-ee-chain-types.workspace = true
strata-identifiers.workspace = true

mockall.workspace = true
