[package]
edition = "2021"
name = "strata-key-derivation"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-primitives.workspace = true

bitcoin = { workspace = true, features = ["rand-std"] }
ed25519-dalek.workspace = true
secp256k1.workspace = true
thiserror.workspace = true
zeroize.workspace = true
