[package]
name = "alpen-open-rpc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
derive-syn-parse = "0.1"
itertools.workspace = true
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
unescape = "0.1"
