[package]
edition = "2021"
name = "alpen-ee-exec-chain"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-ee-common.workspace = true
strata-acct-types.workspace = true

eyre.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-identifiers.workspace = true
strata-ee-acct-types.workspace = true
strata-ee-chain-types.workspace = true
alpen-ee-common = { workspace = true, features = ["test-utils"] }
