[package]
edition = "2021"
name = "strata-ol-rpc-api"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
strata-identifiers.workspace = true
strata-ol-rpc-types.workspace = true
strata-ol-sequencer.workspace = true
strata-primitives.workspace = true

jsonrpsee = { workspace = true, features = ["server", "macros"] }

[features]
client = ["jsonrpsee/client"]
