[package]
name = "strata-snark-acct-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
strata-acct-types.workspace = true
strata-codec.workspace = true

ssz.workspace = true
thiserror.workspace = true

[dev-dependencies]
ssz_derive.workspace = true

[lints]
workspace = true
