[package]
name = "strata-asm-txs-admin"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-asm-params = { workspace = true, features = ["arbitrary"] }
strata-crypto.workspace = true
strata-l1-txfmt.workspace = true
strata-predicate = { workspace = true, features = ["arbitrary"] }
strata-primitives.workspace = true

arbitrary.workspace = true
bitcoin = { workspace = true, optional = true }
borsh.workspace = true
rand = { workspace = true, optional = true }
strata-l1-envelope-fmt.workspace = true
thiserror.workspace = true

[features]
test-utils = ["dep:rand", "dep:bitcoin", "strata-crypto/test-utils"]

[dev-dependencies]
strata-test-utils.workspace = true
