[package]
edition = "2021"
name = "strata-proofimpl-evm-ee-stf"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
alpen-reth-evm.workspace = true
alpen-reth-primitives.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true
zkaleido.workspace = true
zkaleido-native-adapter.workspace = true

alloy-consensus = { workspace = true, features = ["serde-bincode-compat"] }
alloy-eips.workspace = true
reth-chainspec.workspace = true
reth-evm-ethereum.workspace = true
reth-primitives.workspace = true

reth-evm.workspace = true
reth-primitives-traits.workspace = true
reth-trie.workspace = true
revm.workspace = true
revm-primitives.workspace = true
rsp-client-executor.workspace = true
serde.workspace = true


[dev-dependencies]
bincode.workspace = true
serde_json.workspace = true
