[package]
edition = "2021"
name = "strata-l1tx"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-asm-stf.workspace = true
strata-asm-txs-bridge-v1.workspace = true
strata-asm-types.workspace = true
strata-bridge-types.workspace = true
strata-checkpoint-types.workspace = true
strata-crypto.workspace = true
strata-l1-envelope-fmt.workspace = true
strata-ol-chainstate-types.workspace = true
strata-params.workspace = true
strata-primitives.workspace = true

anyhow.workspace = true
bitcoin.workspace = true
borsh.workspace = true
tracing.workspace = true

[dev-dependencies]
strata-btcio = { workspace = true, features = ["test_utils"] }
strata-csm-types.workspace = true
strata-l1-txfmt.workspace = true
strata-test-utils.workspace = true
strata-test-utils-l2.workspace = true

[features]
test_utils = []
