[package]
name = "strata-asm-spec"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-common.workspace = true
strata-asm-proto-bridge-v1.workspace = true
strata-asm-proto-checkpoint.workspace = true
strata-identifiers.workspace = true
strata-l1-txfmt.workspace = true
strata-ol-chainstate-types.workspace = true
strata-params.workspace = true
strata-predicate.workspace = true
strata-primitives.workspace = true
