[package]
name = "strata-asm-proto-administration"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
strata-asm-checkpoint-interface.workspace = true
strata-asm-common.workspace = true
strata-asm-txs-admin.workspace = true
strata-crypto.workspace = true
strata-predicate.workspace = true
strata-primitives.workspace = true

arbitrary.workspace = true
borsh.workspace = true
thiserror.workspace = true

[dev-dependencies]
strata-asm-txs-admin = { workspace = true, features = ["test-utils"] }
strata-test-utils.workspace = true
rand.workspace = true
bitvec.workspace = true
bitcoin.workspace = true
