[package]
edition = "2021"
name = "strata-status"
version = "0.3.0-alpha.1"

[lints]
workspace = true

[dependencies]
strata-csm-types.workspace = true
strata-identifiers.workspace = true
strata-ol-chain-types.workspace = true
strata-ol-chainstate-types.workspace = true
strata-ol-state-types.workspace = true
strata-primitives.workspace = true

thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
